manifest:
  version: 0.1
  projects:
    - name: zmkfirmware
      path: zmk
      remote: https://github.com/zmkfirmware/zmk.git
      revision: main
    - name: zephyr
      path: zephyr
      remote: https://github.com/zephyrproject-rtos/zephyr.git
      revision: main
    - name: libusb
      path: libusb
      remote: https://github.com/libusb/libusb.git
      revision: master
  self:
    path: west
