manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config

build:
  # Ensure a clean build is forced
  clean: true
  config:
    # Add any other build options here
    debug: true
